# Travis CI (https://travis-ci.org/)
# This will only work on your repo if you have an account on travis and you
# have set it up to run continuous integration on this this repo

# Linux distribution (bionic beaver)
dist: bionic

# Language and version
language: python
python:
  - "3.6" # current default Python on Travis CI

cache:
  apt: true # only works with Pro version

env:
  global:
    - OCTFLAGS="--no-gui --no-window-system --silent"

before_install:
  # install octave
  - travis_retry sudo apt-get -y -qq update
  - travis_retry sudo apt-get -y install octave
  - travis_retry sudo apt-get -y install liboctave-dev
  # install SPM and the relevant patches for octave
  - git clone https://github.com/spm/spm12.git --depth 1
  - make -C spm12/src PLATFORM=octave distclean
  - make -C spm12/src PLATFORM=octave
  - make -C spm12/src PLATFORM=octave install
  - octave $OCTFLAGS --eval "addpath(\"spm12\"); savepath ();"
  # install MOX unit
  - git clone https://github.com/MOxUnit/MOxUnit.git --depth 1
  - cd MOxUnit
  - make install
  - cd ..
  # install MOcov
  - git clone https://github.com/MOcov/MOcov.git  --depth 1
  - cd MOcov
  - make install
  - cd ..

script:
  - octave $OCTFLAGS --eval "moxunit_runtests('tests', '-verbose', '-recursive', '-with_coverage', '-cover', 'subfun', '-cover_xml_file', 'coverage.xml'))"
